// AvalonRiscV_QSYS_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module AvalonRiscV_QSYS_mm_interconnect_2 (
		input  wire        clk_0_clk_clk,                                          //                                        clk_0_clk.clk
		input  wire        RISC_V_AVALON_0_reset_sink_reset_bridge_in_reset_reset, // RISC_V_AVALON_0_reset_sink_reset_bridge_in_reset.reset
		input  wire [31:0] RISC_V_AVALON_0_master_instruccions_address,            //              RISC_V_AVALON_0_master_instruccions.address
		output wire        RISC_V_AVALON_0_master_instruccions_waitrequest,        //                                                 .waitrequest
		input  wire        RISC_V_AVALON_0_master_instruccions_read,               //                                                 .read
		output wire [31:0] RISC_V_AVALON_0_master_instruccions_readdata,           //                                                 .readdata
		input  wire        RISC_V_AVALON_0_master_instruccions_write,              //                                                 .write
		input  wire [31:0] RISC_V_AVALON_0_master_instruccions_writedata,          //                                                 .writedata
		input  wire        RISC_V_AVALON_0_master_instruccions_lock,               //                                                 .lock
		output wire [9:0]  instruccionMemory_s1_address,                           //                             instruccionMemory_s1.address
		output wire        instruccionMemory_s1_write,                             //                                                 .write
		input  wire [31:0] instruccionMemory_s1_readdata,                          //                                                 .readdata
		output wire [31:0] instruccionMemory_s1_writedata,                         //                                                 .writedata
		output wire [3:0]  instruccionMemory_s1_byteenable,                        //                                                 .byteenable
		output wire        instruccionMemory_s1_chipselect,                        //                                                 .chipselect
		output wire        instruccionMemory_s1_clken                              //                                                 .clken
	);

	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_waitrequest;   // instruccionMemory_s1_translator:uav_waitrequest -> RISC_V_AVALON_0_master_instruccions_translator:uav_waitrequest
	wire  [31:0] risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdata;      // instruccionMemory_s1_translator:uav_readdata -> RISC_V_AVALON_0_master_instruccions_translator:uav_readdata
	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_debugaccess;   // RISC_V_AVALON_0_master_instruccions_translator:uav_debugaccess -> instruccionMemory_s1_translator:uav_debugaccess
	wire  [31:0] risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_address;       // RISC_V_AVALON_0_master_instruccions_translator:uav_address -> instruccionMemory_s1_translator:uav_address
	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_read;          // RISC_V_AVALON_0_master_instruccions_translator:uav_read -> instruccionMemory_s1_translator:uav_read
	wire   [3:0] risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_byteenable;    // RISC_V_AVALON_0_master_instruccions_translator:uav_byteenable -> instruccionMemory_s1_translator:uav_byteenable
	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdatavalid; // instruccionMemory_s1_translator:uav_readdatavalid -> RISC_V_AVALON_0_master_instruccions_translator:uav_readdatavalid
	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_lock;          // RISC_V_AVALON_0_master_instruccions_translator:uav_lock -> instruccionMemory_s1_translator:uav_lock
	wire         risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_write;         // RISC_V_AVALON_0_master_instruccions_translator:uav_write -> instruccionMemory_s1_translator:uav_write
	wire  [31:0] risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_writedata;     // RISC_V_AVALON_0_master_instruccions_translator:uav_writedata -> instruccionMemory_s1_translator:uav_writedata
	wire   [2:0] risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_burstcount;    // RISC_V_AVALON_0_master_instruccions_translator:uav_burstcount -> instruccionMemory_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) risc_v_avalon_0_master_instruccions_translator (
		.clk                    (clk_0_clk_clk),                                                                          //                       clk.clk
		.reset                  (RISC_V_AVALON_0_reset_sink_reset_bridge_in_reset_reset),                                 //                     reset.reset
		.uav_address            (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (RISC_V_AVALON_0_master_instruccions_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (RISC_V_AVALON_0_master_instruccions_waitrequest),                                        //                          .waitrequest
		.av_read                (RISC_V_AVALON_0_master_instruccions_read),                                               //                          .read
		.av_readdata            (RISC_V_AVALON_0_master_instruccions_readdata),                                           //                          .readdata
		.av_write               (RISC_V_AVALON_0_master_instruccions_write),                                              //                          .write
		.av_writedata           (RISC_V_AVALON_0_master_instruccions_writedata),                                          //                          .writedata
		.av_lock                (RISC_V_AVALON_0_master_instruccions_lock),                                               //                          .lock
		.av_burstcount          (1'b1),                                                                                   //               (terminated)
		.av_byteenable          (4'b1111),                                                                                //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                   //               (terminated)
		.av_begintransfer       (1'b0),                                                                                   //               (terminated)
		.av_chipselect          (1'b0),                                                                                   //               (terminated)
		.av_readdatavalid       (),                                                                                       //               (terminated)
		.av_debugaccess         (1'b0),                                                                                   //               (terminated)
		.uav_clken              (),                                                                                       //               (terminated)
		.av_clken               (1'b1),                                                                                   //               (terminated)
		.uav_response           (2'b00),                                                                                  //               (terminated)
		.av_response            (),                                                                                       //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                   //               (terminated)
		.av_writeresponsevalid  ()                                                                                        //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) instruccionmemory_s1_translator (
		.clk                    (clk_0_clk_clk),                                                                          //                      clk.clk
		.reset                  (RISC_V_AVALON_0_reset_sink_reset_bridge_in_reset_reset),                                 //                    reset.reset
		.uav_address            (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (risc_v_avalon_0_master_instruccions_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (instruccionMemory_s1_address),                                                           //      avalon_anti_slave_0.address
		.av_write               (instruccionMemory_s1_write),                                                             //                         .write
		.av_readdata            (instruccionMemory_s1_readdata),                                                          //                         .readdata
		.av_writedata           (instruccionMemory_s1_writedata),                                                         //                         .writedata
		.av_byteenable          (instruccionMemory_s1_byteenable),                                                        //                         .byteenable
		.av_chipselect          (instruccionMemory_s1_chipselect),                                                        //                         .chipselect
		.av_clken               (instruccionMemory_s1_clken),                                                             //                         .clken
		.av_read                (),                                                                                       //              (terminated)
		.av_begintransfer       (),                                                                                       //              (terminated)
		.av_beginbursttransfer  (),                                                                                       //              (terminated)
		.av_burstcount          (),                                                                                       //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                   //              (terminated)
		.av_waitrequest         (1'b0),                                                                                   //              (terminated)
		.av_writebyteenable     (),                                                                                       //              (terminated)
		.av_lock                (),                                                                                       //              (terminated)
		.uav_clken              (1'b0),                                                                                   //              (terminated)
		.av_debugaccess         (),                                                                                       //              (terminated)
		.av_outputenable        (),                                                                                       //              (terminated)
		.uav_response           (),                                                                                       //              (terminated)
		.av_response            (2'b00),                                                                                  //              (terminated)
		.uav_writeresponsevalid (),                                                                                       //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                    //              (terminated)
	);

endmodule
